# PANDAS 01
Practica con pandas local usando entorno creado con venv y jupyter notebooks

In [19]:
import pandas as pd 

def sep(guiones:int=50) -> None:
    '''Separador simple rapido'''
    print('-' * guiones)

# pruebas numpy
#import numpy as np 

#x=25
#print(f'La raiz cuadrada de {x} es {np.sqrt(x)}')
#print(type( np.sqrt(x) ))

#print( 5.0 + np.sqrt(25))
#print(type(5.0))
#print( type(5.0 + np.sqrt(25) ))

primero veremos los dataframes

In [20]:
# una forma de crear una tabla es usando una lista de listas
# primero especificamos los nombres de las columnas
columnas = ['Nombre','Edad','Ocupacion']

datos = [
    ['Bruno',29,'Ingeniero'],
    ['Pablo',35,'Medico'],
    ['Maria',23,'Abogada']
]

df = pd.DataFrame(data=datos, columns=columnas)
df

  Nombre  Edad  Ocupacion
0  Bruno    29  Ingeniero
1  Pablo    35     Medico
2  Maria    23    Abogada

Otro tipo de datos de padnas es una Serie, que es basicamente una columna del dataframe

In [21]:
# formas de seleccionar una Serie :
print( df["Edad"] ) # Usando indice (Indexing) # este es el metodo PREFERIDO
sep(25)
print( df.Edad ) # Usando referencia al atributo

0    29
1    35
2    23
Name: Edad, dtype: int64
-------------------------
0    29
1    35
2    23
Name: Edad, dtype: int64

## dtypes
Son los tipos de datos de pandas. Basicamente indican el tipo de operaciones que se pueden hacer con toda la serie

In [22]:
# ejemplo df con columnas/series de tipos distintos
columnas1 = ['TipoEntero','TipoDecimal','TipoCadena','TipoBooleano','TipoMixto']
datos1 = [
    [1,1.0,'A',True,'a'],
    [2,1.5,'B',False,15],
    [3,-1.5,'C',False,True]
]
df1 = pd.DataFrame(columns=columnas1, data=datos1)
print(df1)
sep()
print(df1['TipoEntero'])
sep()
print(df1['TipoDecimal'])
sep()
print(df1['TipoCadena'])
sep()
print(df1['TipoBooleano'])
sep()
print(df1['TipoMixto'])

   TipoEntero  TipoDecimal TipoCadena  TipoBooleano TipoMixto
0           1          1.0          A          True         a
1           2          1.5          B         False        15
2           3         -1.5          C         False      True
--------------------------------------------------
0    1
1    2
2    3
Name: TipoEntero, dtype: int64
--------------------------------------------------
0    1.0
1    1.5
2   -1.5
Name: TipoDecimal, dtype: float64
--------------------------------------------------
0    A
1    B
2    C
Name: TipoCadena, dtype: str
--------------------------------------------------
0     True
1    False
2    False
Name: TipoBooleano, dtype: bool
--------------------------------------------------
0       a
1      15
2    True
Name: TipoMixto, dtype: object

Podemos ver el tipo de datos (dtype) de cada columna de nuestro dataframe mediante su atributo dtypes

In [23]:
df1.dtypes

TipoEntero        int64
TipoDecimal     float64
TipoCadena          str
TipoBooleano       bool
TipoMixto        object
dtype: object

Podemos hacer operaciones sobre SERIES que son de cierto tipo de dtype compatibles entre si. Las operaciones actuan elemento por elemento

In [24]:
# recordando
print('df:')
print(df)
sep()
print('df1:')
print(df1)
sep()

#Ejemplo de operaciones entre series
df['Edad'] + df1['TipoDecimal']

df:
  Nombre  Edad  Ocupacion
0  Bruno    29  Ingeniero
1  Pablo    35     Medico
2  Maria    23    Abogada
--------------------------------------------------
df1:
   TipoEntero  TipoDecimal TipoCadena  TipoBooleano TipoMixto
0           1          1.0          A          True         a
1           2          1.5          B         False        15
2           3         -1.5          C         False      True
--------------------------------------------------

0    30.0
1    36.5
2    21.5
dtype: float64

In [25]:
# tambien puedo usar para operaciones basicas
df1["TipoEntero"] * 10 + 1000

0    1010
1    1020
2    1030
Name: TipoEntero, dtype: int64

Como seleccionar un valor de una SERIE

In [26]:
print("df1['TipoEntero'][0]: ",df1['TipoEntero'][0])
print("df1['TipoEntero'][1]: ",df1['TipoEntero'][1])

# esto no funcionara, porque pandas usa su indice automatico (RangeIndex) que va de 0 a N (sin numeros negativos):
#   print(df1['TipoEntero'][-1]) ### DA ERROR
# una forma de obtener ese dato es usar 'iloc' (integer location) que nos permite obtener la posicion fisica asi como con las listas en py
print("df1['TipoEntero'].iloc[-1]: ",df1['TipoEntero'].iloc[-1])

df1['TipoEntero'][0]:  1
df1['TipoEntero'][1]:  2
df1['TipoEntero'].iloc[-1]:  3

Aparte de seleccionar una unica columna de un dataframe (lo que nos devuelve una serie), podemos tambien seleccionar un SUBSET de columnas

In [27]:
df1[["TipoEntero","TipoBooleano"]]

   TipoEntero  TipoBooleano
0           1          True
1           2         False
2           3         False

In [28]:
# Ojo, notar que es una lista dentro del df[ ] , esto no funciona:
# df1["TipoEntero","TipoBooleano"] # DEVUELVE ERROR

Las modificaciones que se realizan sobre un dataframe no son permanentes al menos que sobre escribamos ese mismo dataframe

In [29]:
df1.drop("TipoEntero",axis=1)

   TipoDecimal TipoCadena  TipoBooleano TipoMixto
0          1.0          A          True         a
1          1.5          B         False        15
2         -1.5          C         False      True

In [30]:
# Nota: axis=1 sirve para borrar toda la columna (Serie) . Si pongo axis=0 lo que hace es buscar el indice y borrar una fila
df1.drop(1,axis=0)

   TipoEntero  TipoDecimal TipoCadena  TipoBooleano TipoMixto
0           1          1.0          A          True         a
2           3         -1.5          C         False      True

In [31]:
# volviendo al ejemplo anterior, aca podemos ver como mi df1 NO fue modificado. Esto es porque .drop me genero un NUEVO DATAFRAME con el cambio que le pedi
df1

   TipoEntero  TipoDecimal TipoCadena  TipoBooleano TipoMixto
0           1          1.0          A          True         a
1           2          1.5          B         False        15
2           3         -1.5          C         False      True

si realmente queremos modificar nuestro df1...

In [32]:
# primero lo voy a backupear 
df1_backup = df1.copy() # ojo, el backup no funciona sin el .copy

podemos hacerlo asi:

In [33]:
df1 = df1.drop('TipoCadena',axis=1) 
df1

   TipoEntero  TipoDecimal  TipoBooleano TipoMixto
0           1          1.0          True         a
1           2          1.5         False        15
2           3         -1.5         False      True

In [34]:
# voy a restaurarlo
df1 = df1_backup
df1

   TipoEntero  TipoDecimal TipoCadena  TipoBooleano TipoMixto
0           1          1.0          A          True         a
1           2          1.5          B         False        15
2           3         -1.5          C         False      True

o podriamos usar INPLACE:

In [35]:
df1.drop('TipoCadena',axis=1,inplace=True) 
df1

   TipoEntero  TipoDecimal  TipoBooleano TipoMixto
0           1          1.0          True         a
1           2          1.5         False        15
2           3         -1.5         False      True

In [36]:
# voy a restaurarlo
df1 = df1_backup
df1

   TipoEntero  TipoDecimal  TipoBooleano TipoMixto
0           1          1.0          True         a
1           2          1.5         False        15
2           3         -1.5         False      True