# PANDAS 02
Practica mas avanzada de Pandas

In [73]:
import pandas as pd 
df = pd.read_csv('personas.csv',delimiter=';')
df

,ID_Persona,Nombre,Edad,Ocupacion,Salario,Ciudad,Fecha_Contratacion,Puntaje_Desempenio
0,1,Antonio,18,Estudiante,NaN,Rosario,2023-04-05,1.4
1,2,Maria,30,Ingeniera,2500.0,Cordoba,2017-06-14,1.9
2,3,Mauro,25,Plomero,1450.0,Mar del Plata,2017-06-21,2.8
3,4,Gaston,28,ingeniero,2000.0,Rosario,2017-05-31,4.8
4,5,Alfredo,45,Medico,2100.0,Resistencia,2017-12-19,4.2
...,...,...,...,...,...,...,...,...
95,96,Maria,27,Ingeniero,4322.0,Tucuman,2015-12-15,5.0
96,97,Carlos,56,Desarrollador,4238.0,Santa Fe,2019-04-08,2.8
97,98,Valeria,45,Plomero,3329.0,Resistencia,2023-04-20,1.4
98,99,Sofia,34,Abogado,1332.0,Rosario,2021-03-10,1.3
99,100,Elena,62,Desarrollador,2924.0,Mendoza,2018-03-26,3.8

Podemos revisar los primeros 5 y ultimos 5 registros para tener una idea de la data

In [74]:
df.head()

,ID_Persona,Nombre,Edad,Ocupacion,Salario,Ciudad,Fecha_Contratacion,Puntaje_Desempenio
0,1,Antonio,18,Estudiante,NaN,Rosario,2023-04-05,1.4
1,2,Maria,30,Ingeniera,2500.0,Cordoba,2017-06-14,1.9
2,3,Mauro,25,Plomero,1450.0,Mar del Plata,2017-06-21,2.8
3,4,Gaston,28,ingeniero,2000.0,Rosario,2017-05-31,4.8
4,5,Alfredo,45,Medico,2100.0,Resistencia,2017-12-19,4.2

In [75]:
df.tail()

,ID_Persona,Nombre,Edad,Ocupacion,Salario,Ciudad,Fecha_Contratacion,Puntaje_Desempenio
95,96,Maria,27,Ingeniero,4322.0,Tucuman,2015-12-15,5.0
96,97,Carlos,56,Desarrollador,4238.0,Santa Fe,2019-04-08,2.8
97,98,Valeria,45,Plomero,3329.0,Resistencia,2023-04-20,1.4
98,99,Sofia,34,Abogado,1332.0,Rosario,2021-03-10,1.3
99,100,Elena,62,Desarrollador,2924.0,Mendoza,2018-03-26,3.8

## renombrado de columnas
Podemos renombrar columnas del dataframe usando rename.
Para eso, pasamos un DICCIONARIO que tiene key=nombre_viejo , value=nombre_nuevo

In [76]:
df_con_renombres = df.rename(columns={"Ocupacion":"Trabajo","Salario":"Ingresos"})
df_con_renombres.head()
# si quisieramos editar el mismo dataframe en si, pondiamos [ df = df.rename(... ]

,ID_Persona,Nombre,Edad,Trabajo,Ingresos,Ciudad,Fecha_Contratacion,Puntaje_Desempenio
0,1,Antonio,18,Estudiante,NaN,Rosario,2023-04-05,1.4
1,2,Maria,30,Ingeniera,2500.0,Cordoba,2017-06-14,1.9
2,3,Mauro,25,Plomero,1450.0,Mar del Plata,2017-06-21,2.8
3,4,Gaston,28,ingeniero,2000.0,Rosario,2017-05-31,4.8
4,5,Alfredo,45,Medico,2100.0,Resistencia,2017-12-19,4.2

## Filtrado de columnas
Podemos filtrar los elementos de un dataframe.
Para ello, dentro de la definicion de dataframe vamos a tener que generar una SERIE de True/Falses (una Serie de tipo Booleano) que nos indiquen que filas se van a tomar y cuales no.... Las filas con True se toman mientras que las que den False no se toman.

En un ejemplo paso a paso esto quedaria asi:

In [77]:
# recordando la estructura original:
df.head(3)

,ID_Persona,Nombre,Edad,Ocupacion,Salario,Ciudad,Fecha_Contratacion,Puntaje_Desempenio
0,1,Antonio,18,Estudiante,NaN,Rosario,2023-04-05,1.4
1,2,Maria,30,Ingeniera,2500.0,Cordoba,2017-06-14,1.9
2,3,Mauro,25,Plomero,1450.0,Mar del Plata,2017-06-21,2.8

In [78]:
# Quiero filtar todos aquellos registros con edades mayores a 45
# Lo voy viendo paso a paso
# Tengo esta Serie que es mi columna edad:
serie_edades = df["Edad"]
serie_edades.head(5)

0    18
1    30
2    25
3    28
4    45
Name: Edad, dtype: int64

In [79]:
# puedo generar una serie de booleanos pasandole una condicion
serie_booleanos_condicion = serie_edades >= 45
serie_booleanos_condicion.head(5)

0    False
1    False
2    False
3    False
4     True
Name: Edad, dtype: bool

In [80]:
# y si ahora, uso esa serie de booleanos en mi df, obtengo el df filtrado
df_filtrado = df[serie_booleanos_condicion]
df_filtrado.head(5)

,ID_Persona,Nombre,Edad,Ocupacion,Salario,Ciudad,Fecha_Contratacion,Puntaje_Desempenio
4,5,Alfredo,45,Medico,2100.0,Resistencia,2017-12-19,4.2
8,9,Pedro,62,Vendedor,3799.0,Resistencia,2022-02-13,1.7
9,10,Lucia,47,Médica,NaN,Santa Fe,2017-06-18,3.7
11,12,Valeria,63,Medico,1870.0,Mar del Plata,2022-03-18,2.8
12,13,Juan,65,Analista,3207.0,Resistencia,2019-10-21,4.6

In [81]:
# puedo hacer todo esto de forma mas visual directamente asi:
# df_filtrado = df[ (serie de booleanos generada por una condicion) ]
df_filtrado   = df[ df['Edad'] >= 45 ]
df_filtrado.head(5)

,ID_Persona,Nombre,Edad,Ocupacion,Salario,Ciudad,Fecha_Contratacion,Puntaje_Desempenio
4,5,Alfredo,45,Medico,2100.0,Resistencia,2017-12-19,4.2
8,9,Pedro,62,Vendedor,3799.0,Resistencia,2022-02-13,1.7
9,10,Lucia,47,Médica,NaN,Santa Fe,2017-06-18,3.7
11,12,Valeria,63,Medico,1870.0,Mar del Plata,2022-03-18,2.8
12,13,Juan,65,Analista,3207.0,Resistencia,2019-10-21,4.6

mas ejemplos de filtros posibles

In [ ]:
# condiciones multiples
# ejs: medicos que ganen mas de 2100
df_filtrado = df[( (df['Ocupacion'] == 'Medico') | (df['Ocupacion'] == 'Medica') ) & ( df['Salario'] > 1800 ) ]
df_filtrado
# (notar como no aparece el registro 9 de arriba, mas adelante veremos como hacer limpieza de datos)

,ID_Persona,Nombre,Edad,Ocupacion,Salario,Ciudad,Fecha_Contratacion,Puntaje_Desempenio
4,5,Alfredo,45,Medico,2100.0,Resistencia,2017-12-19,4.2
11,12,Valeria,63,Medico,1870.0,Mar del Plata,2022-03-18,2.8
75,76,Jorge,21,Medico,1918.0,Buenos Aires,2023-06-17,1.1

In [ ]:
# filtrando como si fuera con sql
# OJO: los operadores OR, AND van en MINUSCULAS
df_filtrado = df.query(" ((Ocupacion == 'Medico') or ( Ocupacion == 'Medica')) and Salario > 1800 ")
df_filtrado

,ID_Persona,Nombre,Edad,Ocupacion,Salario,Ciudad,Fecha_Contratacion,Puntaje_Desempenio
4,5,Alfredo,45,Medico,2100.0,Resistencia,2017-12-19,4.2
11,12,Valeria,63,Medico,1870.0,Mar del Plata,2022-03-18,2.8
75,76,Jorge,21,Medico,1918.0,Buenos Aires,2023-06-17,1.1

In [91]:
# o sino 
df_filtrado = df.query(" Ocupacion in ['Medico' ,'Medica'] and Salario > 1800 ")
df_filtrado

,ID_Persona,Nombre,Edad,Ocupacion,Salario,Ciudad,Fecha_Contratacion,Puntaje_Desempenio
4,5,Alfredo,45,Medico,2100.0,Resistencia,2017-12-19,4.2
11,12,Valeria,63,Medico,1870.0,Mar del Plata,2022-03-18,2.8
75,76,Jorge,21,Medico,1918.0,Buenos Aires,2023-06-17,1.1

In [ ]:
# filtrando casos que comopiencen con una letra
df_filtrado = df[df["Nombre"].str.startswith('A')]
df_filtrado.head(3)

,ID_Persona,Nombre,Edad,Ocupacion,Salario,Ciudad,Fecha_Contratacion,Puntaje_Desempenio
0,1,Antonio,18,Estudiante,NaN,Rosario,2023-04-05,1.4
4,5,Alfredo,45,Medico,2100.0,Resistencia,2017-12-19,4.2
15,16,Antonio,61,Arquitecta,1469.0,Santa Fe,2023-06-03,2.1

In [95]:
# solo asi puedo hacer un 'RLIKE'
df_filtrado = df[ df["Nombre"].str.contains('^a.*o$', case=False, regex=True, na=False) ]
df_filtrado.head(3)

,ID_Persona,Nombre,Edad,Ocupacion,Salario,Ciudad,Fecha_Contratacion,Puntaje_Desempenio
0,1,Antonio,18,Estudiante,NaN,Rosario,2023-04-05,1.4
4,5,Alfredo,45,Medico,2100.0,Resistencia,2017-12-19,4.2
15,16,Antonio,61,Arquitecta,1469.0,Santa Fe,2023-06-03,2.1